FIELDS_GROUP_DIC = {
    "MathLogic": [
        "abstract_algebra",
        "elementary_mathematics",
        "college_mathematics",
        "high_school_mathematics",
        "high_school_statistics",
        "formal_logic",
        "logical_fallacies",
    ],
    "SciEng": [
        "astronomy",
        "conceptual_physics",
        "high_school_physics",
        "college_physics",
        "high_school_chemistry",
        "college_chemistry",
        "electrical_engineering",
    ],
    "Computing": [
        "computer_security",
        "college_computer_science",
        "high_school_computer_science",
        "machine_learning",
    ],
    "LifeSci": [
        "college_biology",
        "high_school_biology",
        "human_aging",
        "nutrition",
        "virology",
        "medical_genetics",
    ],
    "Health": [
        "clinical_knowledge",
        "college_medicine",
        "professional_medicine",
        "professional_psychology",
        "human_sexuality",
        "high_school_psychology",
        "anatomy",
    ],
    "BusinessEcon": [
        "business_ethics",
        "management",
        "marketing",
        "professional_accounting",
        "high_school_macroeconomics",
        "high_school_microeconomics",
        "econometrics",
    ],
    "Society": [
        "international_law",
        "jurisprudence",
        "professional_law",
        "high_school_government_and_politics",
        "us_foreign_policy",
        "sociology",
        "global_facts",
        "moral_disputes",
        "moral_scenarios",
        "public_relations",
        "security_studies",
    ],
    "Humanities": [
        "high_school_european_history",
        "high_school_us_history",
        "high_school_world_history",
        "high_school_geography",
        "prehistory",
        "philosophy",
        "world_religions",
    ],
    "HighSchool": [
        "high_school_biology",
        "high_school_chemistry",
        "high_school_computer_science",
        "high_school_mathematics",
        "high_school_physics",
    ],
    "College": [
        "college_biology",
        "college_chemistry",
        "college_computer_science",
        "college_mathematics",
        "college_physics",
    ],
}